### ISSUE TITLE
点击下一页会自动刷新页面

### ISSUE THREAD

**Issue by Chise1** [aisuda/amis-admin#74]
点击crud表单的下一页的时候，会自动刷新页面。能不能去掉这个刷新？

**Comment by qq405576297** [comment]
如果你最外层得type="crud" 就会刷新整个页面，你会发现地址栏的链接变了，如加上?page=2;
如果你最外层的type=page的话，则不会刷新整个页面，地址栏的连接也就不会发生变化；
他们这么设计我觉得还是有道理的
你自己选择吧

**Comment by qq405576297** [comment]
> 点击crud表单的下一页的时候，会自动刷新页面。能不能去掉这个刷新？

如果你最外层得type="crud" 就会刷新整个页面，你会发现地址栏的链接变了，如加上?page=2;
如果你最外层的type=page的话，则不会刷新整个页面，地址栏的连接也就不会发生变化；
他们这么设计我觉得还是有道理的
你自己选择吧

**Comment by qq405576297** [comment]
加上"syncLocation": false
