### ISSUE TITLE
怎样使用全局API前缀？

### ISSUE THREAD

**Issue by mingchau** [aisuda/amis-admin#95]
每个请求都用绝对URL，非常不方便。
也不方便切换后端接口环境。

怎样使用全局API前缀？

**Comment by Yansh-vic** [comment]
确实，环境不可能写死的，希望官方能出个例子吧

**Comment by hoyancy** [comment]
可以采用全局变量的方式，先设置 window.API = "api前缀";然后在调用api的时候"url": "${window:API}api后缀",完成替换并请求，版本支持 1.1.6 以上

**Comment by mingchau** [comment]
> Reference in new i

好的，问题解决了~
