### ISSUE TITLE
共性需求：能否在顶部右侧放一个用户名的下拉菜单，下拉包括编辑个人属性和退出。。。

### ISSUE THREAD

**Issue by gillbates** [aisuda/amis-admin#97]
一直在研究怎么搞。。。一直没搞出来

```

            const app = {
                type: 'app',
                brandName: 'Admin',
                // logo: '/public/logo.png',
                header: {
                    "type": "grid",
                    // "className": "b-a bg-dark lter",
                    "columns": [
                        {
                            "md": 10,
                            "body": [
        
                            ]
                        },
                        {
                            "md": 2,
                            "body": [
                                {
                                    "type": "dropdown-button",
                                    "className": "content-end",
                                    "label": "用户XXX",
                                    "trigger": "hover",
                                    "icon": "fa fa-user-circle",
                                    "buttons": [
                                        {
                                            "type": "button",
                                            "label": "个人配置"
                                        },
                                        {
                                            "type": "button",
                                            "label": "退出"
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            };
```

看到代码中

```
      header: {
            type: 'tpl',
            inline: false,
            className: 'w-full',
            tpl: '<div class="flex justify-between"><div>顶部区域左侧</div><div>顶部区域右侧</div></div>'
          },
```

但是放tpl里面又不能采用amis组件了。。。不知道能否帮忙用amis组件实现一个菜单栏屏幕右侧的下拉。。。

**Comment by gillbates** [comment]
`
            const app = {
                type: 'app',
                brandName: 'Admin',
                // logo: '/public/logo.png',
                header: {
                    "type": "flex",
                    "justify": "flex-end",
                    "items": [
                        {
                            "type": "dropdown-button",
                            "className": "content-end",
                            "label": "用户XXX",
                            "trigger": "hover",
                            "icon": "fa fa-user-circle",
                            "buttons": [
                                {
                                    "type": "button",
                                    "label": "个人配置"
                                },
                                {
                                    "type": "button",
                                    "label": "退出"
                                }
                            ]
                        }
                    ]
                },
                footer: '<div class="p-2 text-center bg-light">底部区域</div>'
            };
`

![image](https://user-images.githubusercontent.com/783547/147878299-375bb836-54fd-4d86-84b9-ece4bf957508.png)


试了下，用flex，依然没有居右。。。

**Comment by ly120ve980ly** [comment]
"style": {
    width: "100%"
}
加个宽度设置就可以了
